### ISSUE TITLE
Misleading belongs_to_and_required? warnings in rails 5.2+?

### ISSUE THREAD

**Issue by AlexMouton** [chanzuckerberg/sorbet-rails#255]
**Describe the bug:**
I got a number of warnings generated by belongs_to_and_required? while running rails_rbi:all in a rails 5.2+ codebase.   Not familiar with the code base otherwise but thought id mention it.

**Versions:**
- Ruby: ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]
- Rails: Rails 5.2.4.1
- Sorbet: Sorbet typechecker 0.5.5226 git be978ff1699c36791866272a0c3c5e4f1918c128-dirty built on 2020-01-09 06:30:26 GMT debug_symbols=true
- Sorbet-Rails: 0.5.9.1

**Comment by manhhung741** [comment]
Can you explain why you think it's misleading? 
We show the warning so that people can be consistent about their DB restrictions. It does come up often so maybe we can try to turn it off.

These are the warning shown:

https://github.com/chanzuckerberg/sorbet-rails/blob/master/lib/sorbet-rails/model_plugins/active_record_assoc.rb#L71

**Comment by AlexMouton** [comment]
Hi Harry =)
In the code itself it says that [In Rails 5+, belongs_to are required by default] and exits early.
I am in Rails 5+ but still receiving the second warning message
"specified as not-null at the DB level but **not required** at the application level"

Should I not be exiting out of the function early?

**Comment by manhhung741** [comment]
@AlexMouton The "return false" is not related. It to deal with any association that is not `belongs_to`, because the method is only for checking `belongs_to` connection.

The warning you receive means that:
- The db column has a `null: false` constraint
- But the `belongs_to` association doesn't specify that it's `required: true`, or `optional: false`. Although belongs_to is supposed to be required in Rails 5+, it's possible that your project has `belongs_to_required_by_default` set to false, or the belongs_to association specifies explicitly that it's optional.

I suggest you can ignore the warning messages. It's there to notify you that there are some inconsistencies in the setup only. If it is too noisy, I'll think about removing the warnings.

**Comment by manhhung741** [comment]
Closing for now because the message is intended to be a warning against bad belongs_to setups

**Comment by AlexMouton** [comment]
Thanks  for the breakdown Harry

I think we agree on whats happening here.
In the absense of information to the contrary I think it's mistaken to beg on 'belongs_to_required_by_default' being turned on.  If the default for contemporary Rails is  for required to  be  default: true I think sorbet should presume the same.   The warning directly says "not required at the application level" which is false. 

If nothing else, consider softer language here?

**Comment by manhhung741** [comment]
@AlexMouton 

> In the code it says that [In Rails 5+, belongs_to are required by default] and exits early.
> I am in Rails 5+ but still receiving the second warning message:
> "specified as not-null at the DB level but not required at the application level"

Can you check the value of `belongs_to_required_by_default` config in your codebase? For codebase migration from 4.x up, people might have it set to `false` to preserve the old behavior. 

> If nothing else, consider softer language here?
Please feel free to send a PR to update the language :-)
