### ISSUE TITLE
Can't use action-policy

### ISSUE THREAD

**Issue by jcoyne** [chanzuckerberg/sorbet-rails#381]
**Describe the bug:**
Can't find mixin on controller.
```
app/controllers/works_controller.rb:8: Method verify_authorized does not exist on T.class_of(WorksController) https://srb.help/7003
     8 |  verify_authorized except: [:show]
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    sorbet/rbi/gems/action_policy.rbi:346: Did you mean: ActionPolicy::Controller#verify_authorized?
     346 |  def verify_authorized; end
            ^^^^^^^^^^^^^^^^^^^^^
```

It is added by the railtie here: https://github.com/palkan/action_policy/blob/81455373db9b5fdef533e03871ac4be1cd214077/lib/action_policy/railtie.rb#L88

And the definition is within a `class_methods` block: https://github.com/palkan/action_policy/blob/81455373db9b5fdef533e03871ac4be1cd214077/lib/action_policy/rails/controller.rb#L67

**Steps to reproduce:**

Add `action_policy` to the `Gemfile`, then add `verify_authorized` into a controller

I've run `bundle exec srb rbi hidden-definitions`

and then my `sorbet/rbi/hidden-definitions/hidden.rbi` has:

```ruby
class ActionController::Base
   ...
  include ::ActionPolicy::Controller
end
```
So it's odd that sorbet can't see it.

**Expected behavior:**

It finds this method.

**Versions:**

- Ruby: 2.7.1
- Rails: 6.03.4
- Sorbet: Sorbet typechecker 0.5.5994
- Sorbet-Rails: 0.7.1

**Comment by manhhung741** [comment]
There is a limitation of how Sorbet can understand "include". In short, it doesn't know that `class_methods do` will add class methods to the class (usually `include` only adds instance method to a class).

There is a documentation on sorbet about this:
https://sorbet.org/docs/abstract#interfaces-and-the-included-hook

To fix this, I think you can add an RBI file manually for action_policy. You can contribute to [sorbet-typed](https://github.com/sorbet/sorbet-typed) so that everyone else who uses action-policy can use it.

It looks roughly like this: (please feel free to write a better signature for it)
```ruby
# action_policy.rbi, puts in wherever you want

module ActionPolicy
  module Controller
      module ClassMethods
        extend T::Sig
        extend T::Helpers

        sig { params(options: T.any).void }
        def verify_authorized(**options)
        end

        sig { params(options: T.any).void }
        def skip_verify_authorized(**options)
        end
      end
     mixes_in_class_methods(ClassMethods)
  end
end
```

Let me know if you have any other question!

**Comment by manhhung741** [comment]
Closing this issue because it's a sorbet issue, not sorbet-rails issue
